/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.company;

import com.company.resources.Repository;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author mohamad
 */
public class DifficultyDialog extends javax.swing.JFrame {

    /**
     * Creates new form DifficultyDialog
     */
    public DifficultyDialog() {
        
        initComponents();
        
        initDialog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        difficultyPanel = new javax.swing.JPanel();
        labelWidth = new javax.swing.JLabel();
        widthSpinner = new javax.swing.JSpinner();
        labelHeight = new javax.swing.JLabel();
        heightSpinner = new javax.swing.JSpinner();
        labelMines = new javax.swing.JLabel();
        mineSpinner = new javax.swing.JSpinner();
        startButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        difficultyPanel.setBackground(new java.awt.Color(255, 255, 255));

        labelWidth.setText("JLabel1");

        widthSpinner.setModel(new javax.swing.SpinnerNumberModel(10, 5, 20, 1));

        labelHeight.setText("JLabel2");

        heightSpinner.setModel(new javax.swing.SpinnerNumberModel(10, 5, 20, 1));

        labelMines.setText("JLabel3");

        mineSpinner.setModel(new javax.swing.SpinnerNumberModel(10, 3, 100, 1));

        startButton.setText("jButton1");

        javax.swing.GroupLayout difficultyPanelLayout = new javax.swing.GroupLayout(difficultyPanel);
        difficultyPanel.setLayout(difficultyPanelLayout);
        difficultyPanelLayout.setHorizontalGroup(
            difficultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(difficultyPanelLayout.createSequentialGroup()
                .addGroup(difficultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(difficultyPanelLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(difficultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelWidth)
                            .addComponent(labelHeight)
                            .addComponent(labelMines))
                        .addGap(44, 44, 44)
                        .addGroup(difficultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(mineSpinner)
                            .addComponent(heightSpinner, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(widthSpinner, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(difficultyPanelLayout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(startButton)))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        difficultyPanelLayout.setVerticalGroup(
            difficultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(difficultyPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(difficultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(widthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelWidth))
                .addGap(56, 56, 56)
                .addGroup(difficultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heightSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHeight))
                .addGap(56, 56, 56)
                .addGroup(difficultyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mineSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMines))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(startButton)
                .addContainerGap())
        );

        labelWidth.getAccessibleContext().setAccessibleName("j");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(difficultyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(difficultyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private static DifficultyDialog difficultyDialog;
    private static boolean isInstantiated = false;
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DifficultyDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DifficultyDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DifficultyDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DifficultyDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                difficultyDialog = new DifficultyDialog();
                difficultyDialog.setVisible(true);
            }
        });
    }
    
    /**
     *  function to access DifficultyDialog main instance
     * @return DifficultyDialog difficultyDialog 
     */
    public static DifficultyDialog getInstance() {
            return difficultyDialog;
    } 
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel difficultyPanel;
    private javax.swing.JSpinner heightSpinner;
    private javax.swing.JLabel labelHeight;
    private javax.swing.JLabel labelMines;
    private javax.swing.JLabel labelWidth;
    private javax.swing.JSpinner mineSpinner;
    private javax.swing.JButton startButton;
    private javax.swing.JSpinner widthSpinner;
    // End of variables declaration//GEN-END:variables

    private void initDialog() {
        
        difficultyPanel.setBackground(Repository.colorPurpleDark);
        
        labelWidth.setForeground(Repository.colorGreenLight);
        labelWidth.setFont(Repository.labelFont);
        labelWidth.setText("Width:");
        
        labelHeight.setForeground(Repository.colorGreenLight);
        labelHeight.setFont(Repository.labelFont);
        labelHeight.setText("Height:");
        
        labelMines.setForeground(Repository.colorGreenLight);
        labelMines.setFont(Repository.labelFont);
        labelMines.setText("Mine:");
        
        startButton.setText("Start Game");
        startButton.setForeground(Repository.colorPurpleDark);
        startButton.setBackground(Repository.colorGreenLight);
        
        startButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
                int width = (int)widthSpinner.getValue();
                int height = (int)heightSpinner.getValue();
                int mines = (int)mineSpinner.getValue();
                
                System.out.println("Width: " + width + ", Height: " + height + ", Mines: " + mines);
                
                
                Game.getInstance().startGame(width, height, mines);
            }
        });
        
    }
}
